<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <AssemblyName>D365ForceSaveOnChange</AssemblyName>
    <RootNamespace>D365ForceSaveOnChange</RootNamespace>
    <OutputType>Library</OutputType>

    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>D365ForceSaveOnChange.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="9.0.2.45" />
  </ItemGroup>

</Project>