name: Build Dataverse Plugin DLL

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore D365ForceSaveOnChangePlugin/D365ForceSaveOnChange.csproj

    - name: Build the plugin
      run: msbuild D365ForceSaveOnChangePlugin/D365ForceSaveOnChangePlugin.csproj /p:Configuration=Release

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: D365ForceSaveOnChange
        path: D365ForceSaveOnChangePlugin/bin/Release/**/*.dll
